[tool.poetry]
name = "vdx-helper"
version = "0.1.0"
description = ""
authors = ["Tiago Santos <tiago.santos@vizidox.com>"]

[tool.poetry.dependencies]
python = "^3.6"
werkzeug = "^0.16.0"
requests="2.24.0"
nndict="1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
coverage = "^5.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
